### ISSUE TITLE
Did you test the result in MeViS?

### ISSUE THREAD

**Issue by cocoshe** [ut-vision/ActionVOS#2]

**Comment by oyly16** [comment]
We did not test the result in MeViS, since currently our work focus on egocentric video datasets. Currently, our method take hand-object segmentations as pseudo labels for ActionVOS. This is OK  for ego videos, but difficult to test on MeViS, since MeViS contains videos of moving objects, where hand-object interaction do not exist in most of the MeViS videos.

**Comment by cocoshe** [comment]
> We did not test the result in MeViS, since currently our work focus on egocentric video datasets. Currently, our method take hand-object segmentations as pseudo labels for ActionVOS. This is OK for ego videos, but difficult to test on MeViS, since MeViS contains videos of moving objects, where hand-object interaction do not exist in most of the MeViS videos.

Thanks for your reply~, really a great work on egocentric segmentation with some effective strategies for pseudo labels generation, looking forward to your further work, maybe under a more generalized condition~
